### ISSUE TITLE
Panic: config value conversion

### ISSUE THREAD

**Issue by biefy** [uber-go/fx#335]
While trying to load an integer string to a float64 configuration value, config.Value.PopulateStruct() simply panic:
```
panic: interface conversion: interface is int, not float64
goroutine 1 [running]:
panic(0x944040, 0xc420531ec0)
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:500 +0x1a1
code.uber.internal/devexp/catalyst-backend/vendor/go.uber.org/fx/config.convertValueFromStruct(0x8d1f60, 0xc42063b998, 0xfbd8c0, 0x8c9c60, 0xfbd8c0, 0x8c9c60, 0x8c9c60, 0xc42062d7e0, 0x18e, 0x8d1f60, ...)
	code.uber.internal/devexp/catalyst-backend/vendor/go.uber.org/fx/config/value.go:352 +0x3e0
code.uber.internal/devexp/catalyst-backend/vendor/go.uber.org/fx/config.Value.valueStruct(0xfb78c0, 0xc42062d890, 0xfb7980, 0xc420644480, 0xc420642480, 0x17, 0x92d9a0, 0xc42062c750, 0x1, 0x0, ...)
	code.uber.internal/devexp/catalyst-backend/vendor/go.uber.org/fx/config/value.go:513 +0x63f
code.uber.internal/devexp/catalyst-backend/vendor/go.uber.org/fx/config.Value.PopulateStruct(0xfb78c0, 0xc42062d890, 0xfb7980, 0xc420644480, 0xc420642480, 0x17, 0x92d9a0, 0xc42062c750, 0x1, 0x0, ...)
	code.uber.internal/devexp/catalyst-backend/vendor/go.uber.org/fx/config/value.go:400 +0xf0
code.uber.internal/devexp/catalyst-backend/vendor/go.uber.org/fx/config.Value.valueStruct(0xfb78c0, 0xc42062d6e0, 0xfb7980, 0xc4206443c0, 0xc420644300, 0xf, 0x92d9a0, 0xc42062c300, 0x1, 0x0, ...)
	code.uber.internal/devexp/catalyst-backend/vendor/go.uber.org/fx/config/value.go:524 +0x1fba
code.uber.internal/devexp/catalyst-backend/vendor/go.uber.org/fx/config.Value.PopulateStruct(0xfb78c0, 0xc42062d6e0, 0xfb7980, 0xc4206443c0, 0xc420644300, 0xf, 0x92d9a0, 0xc42062c300, 0x1, 0x0, ...)
	code.uber.internal/devexp/catalyst-backend/vendor/go.uber.org/fx/config/value.go:400 +0xf0
code.uber.internal/devexp/catalyst-backend/vendor/go.uber.org/fx/config.Value.valueStruct(0xfb78c0, 0xc42062d650, 0xfb7980, 0xc4206442f0, 0xa5baa7, 0x8, 0x92d9a0, 0xc42062c2a0, 0x1, 0x0, ...)
	code.uber.internal/devexp/catalyst-backend/vendor/go.uber.org/fx/config/value.go:524 +0x1fba
code.uber.internal/devexp/catalyst-backend/vendor/go.uber.org/fx/config.Value.PopulateStruct(0xfb78c0, 0xc42062d650, 0xfb7980, 0xc4206442f0, 0xa5baa7, 0x8, 0x92d9a0, 0xc42062c2a0, 0x1, 0x0, ...)
	code.uber.internal/devexp/catalyst-backend/vendor/go.uber.org/fx/config/value.go:400 +0xf0
```

A value in the form of an integer, e.g. "1" should be seamlessly converted to a float value with no issue. 

Also, it took me quite a while to figure out the actual offending key.  It would have saved me the time if key name is part of the failure message.

To reproduce the problem, simply create a config struct containing a float64 member, then call Value.PopulateStruct() to feed that value with any config provider reading data from an integer string.

**Comment by sectioneight** [comment]
Please follow our feedback instructions for our internal docs, specifically
don't reference any internal code in public github.
