### ISSUE TITLE
long-running goroutines started in OnStart hooks can leak without a done channel

### ISSUE THREAD

**Issue by zmt** [uber-go/fx#794]
### Problem Statement
If an OnStart hook kicks off a long-running goroutine which breaks the context chain from `app.Start()`, there is no way to signal that goroutine to stop (in test or production).

### Proposal
It would facilitate clean shutdown as well as leak testing to make `app.Done()` available within the `fx.Lifecycle` so `Hook`s can spawn well-behaved goroutines which respond to a shutdown signal.

### Trivial Example
Here's verbose test output from the trivial example in attached `fxonstartleak.zip`:
```lang=bash
% go test -v .
=== RUN   TestOpts
    writer.go:40: [Fx] PROVIDE  fx.Lifecycle <= go.uber.org/fx.New.func1()
    writer.go:40: [Fx] PROVIDE  fx.Shutdowner <= go.uber.org/fx.(*App).shutdowner-fm()
    writer.go:40: [Fx] PROVIDE  fx.DotGraph <= go.uber.org/fx.(*App).dotGraph-fm()
    writer.go:40: [Fx] LOGGER   Initialized custom logger from go.uber.org/fx/fxtest.New.func1()
    writer.go:40: [Fx] INVOKE           zmt.org/fxonstartleak.leakyOnStart()
    writer.go:40: [Fx] INVOKE           zmt.org/fxonstartleak.shutdownOnStart()
    writer.go:40: [Fx] HOOK OnStart             zmt.org/fxonstartleak.leakyOnStart.func1() executing (caller: zmt.org/fxonstartleak.leakyOnStart)
    writer.go:40: [Fx] HOOK OnStart             zmt.org/fxonstartleak.leakyOnStart.func1() called by zmt.org/fxonstartleak.leakyOnStart ran successfully in 2.06µs
in OnStart goroutine
    writer.go:40: [Fx] HOOK OnStart             zmt.org/fxonstartleak.shutdownOnStart.func1() executing (caller: zmt.org/fxonstartleak.shutdownOnStart)
calling Shutdown in OnStart hook
    writer.go:40: [Fx] HOOK OnStart             zmt.org/fxonstartleak.shutdownOnStart.func1() called by zmt.org/fxonstartleak.shutdownOnStart ran successfully in 2.675µs
    writer.go:40: [Fx] RUNNING
--- PASS: TestOpts (0.00s)
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 20 in state chan receive, with zmt.org/fxonstartleak.leakyOnStart.func1.1 on top of the stack:
goroutine 20 [chan receive]:
zmt.org/fxonstartleak.leakyOnStart.func1.1(0x13515e0, 0xc000184118)
        /Users/ztrain/tmp/fxonstartleak/main.go:37 +0xe9
created by zmt.org/fxonstartleak.leakyOnStart.func1
        /Users/ztrain/tmp/fxonstartleak/main.go:32 +0x47
]
FAIL    zmt.org/fxonstartleak   0.990s
```
[fxonstartleak.zip](https://github.com/uber-go/fx/files/7261619/fxonstartleak.zip)

**Comment by zmt** [comment]
In my real code, I was calling the cancel from an `OnStop` hook but made an error reducing to the trivial example. I thought I had something. It doesn't leak when I patch the example thusly:
```
diff --git a/main.go b/main.go
index fae0413..5f4106f 100644
--- a/main.go
+++ b/main.go
@@ -27,20 +27,24 @@ func opts() fx.Option {
 }

 func leakyOnStart(lc fx.Lifecycle, shutdowner fx.Shutdowner) {
+       bgCtx, bgCancel := context.WithTimeout(context.Background(), time.Second)
        lc.Append(fx.Hook{
                OnStart: func(ctx context.Context) error {
                        go func() {
                                fmt.Println("in OnStart goroutine")
-                               ctx, cancel := context.WithTimeout(context.Background(), time.Second)
-                               defer cancel()
+                               defer bgCancel()
                                select {
-                               case <-ctx.Done():
+                               case <-bgCtx.Done():
                                        fmt.Println("context done in OnStart goroutine")
                                        shutdowner.Shutdown()
                                }
                        }()
                        return nil
                },
+               OnStop: func(ctx context.Context) error {
+                       bgCancel()
+                       return nil
+               },
        })
 }
```

```
% go test -v .
=== RUN   TestOpts
    writer.go:40: [Fx] PROVIDE	fx.Lifecycle <= go.uber.org/fx.New.func1()
    writer.go:40: [Fx] PROVIDE	fx.Shutdowner <= go.uber.org/fx.(*App).shutdowner-fm()
    writer.go:40: [Fx] PROVIDE	fx.DotGraph <= go.uber.org/fx.(*App).dotGraph-fm()
    writer.go:40: [Fx] LOGGER	Initialized custom logger from go.uber.org/fx/fxtest.New.func1()
    writer.go:40: [Fx] INVOKE		zmt.org/fxonstartleak.leakyOnStart()
    writer.go:40: [Fx] INVOKE		zmt.org/fxonstartleak.shutdownOnStart()
    writer.go:40: [Fx] HOOK OnStart		zmt.org/fxonstartleak.leakyOnStart.func1() executing (caller: zmt.org/fxonstartleak.leakyOnStart)
    writer.go:40: [Fx] HOOK OnStart		zmt.org/fxonstartleak.leakyOnStart.func1() called by zmt.org/fxonstartleak.leakyOnStart ran successfully in 2.611µs
in OnStart goroutine
    writer.go:40: [Fx] HOOK OnStart		zmt.org/fxonstartleak.shutdownOnStart.func1() executing (caller: zmt.org/fxonstartleak.shutdownOnStart)
calling Shutdown in OnStart hook
    writer.go:40: [Fx] HOOK OnStart		zmt.org/fxonstartleak.shutdownOnStart.func1() called by zmt.org/fxonstartleak.shutdownOnStart ran successfully in 2.405µs
    writer.go:40: [Fx] RUNNING
    writer.go:40: [Fx] HOOK OnStop		zmt.org/fxonstartleak.leakyOnStart.func2() executing (caller: zmt.org/fxonstartleak.leakyOnStart)
    writer.go:40: [Fx] HOOK OnStop		zmt.org/fxonstartleak.leakyOnStart.func2() called by zmt.org/fxonstartleak.leakyOnStart ran successfully in 2.005µs
context done in OnStart goroutine
--- PASS: TestOpts (0.00s)
PASS
```

I have some other goroutine leak in my real code...
